"""Add token_id and techSize column to Sale

Revision ID: 1b28355d5dea
Revises: 6a017a8ca582
Create Date: 2025-03-01 19:41:39.752927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b28355d5dea'
down_revision: Union[str, None] = '6a017a8ca582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('techSize', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'techSize')
    # ### end Alembic commands ###
