"""Add token_id in Stock

Revision ID: 2fb1313a3356
Revises: a5aecd6f24f9
Create Date: 2025-03-07 10:58:19.004057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb1313a3356'
down_revision: Union[str, None] = 'a5aecd6f24f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('token_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stocks', 'tokens', ['token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_column('stocks', 'token_id')
    # ### end Alembic commands ###
