"""Add notify_incomes  in User

Revision ID: 3e71250dcbf0
Revises: 6b8c088daec5
Create Date: 2025-03-11 15:02:10.039136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e71250dcbf0'
down_revision: Union[str, None] = '6b8c088daec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notify_incomes', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_incomes')
    # ### end Alembic commands ###
