"""Add token_id column to product

Revision ID: 6a017a8ca582
Revises: d548fff69967
Create Date: 2025-03-01 16:01:12.053487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a017a8ca582'
down_revision: Union[str, None] = 'd548fff69967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('token_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'tokens', ['token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'token_id')
    # ### end Alembic commands ###
