"""Add token_id in Product_positions

Revision ID: 6a31ce884d1c
Revises: 2fb1313a3356
Create Date: 2025-03-07 12:56:23.063752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a31ce884d1c'
down_revision: Union[str, None] = '2fb1313a3356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_positions', sa.Column('token_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product_positions', 'tokens', ['token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_positions', type_='foreignkey')
    op.drop_column('product_positions', 'token_id')
    # ### end Alembic commands ###
