"""Add notify_daily_report in User

Revision ID: 6b8c088daec5
Revises: 6a31ce884d1c
Create Date: 2025-03-09 17:08:43.695502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8c088daec5'
down_revision: Union[str, None] = '6a31ce884d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notify_daily_report', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_daily_report')
    # ### end Alembic commands ###
