"""Add Token table and token_id in users

Revision ID: 707f74e00c62
Revises: 
Create Date: 2025-02-28 21:48:34.518284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707f74e00c62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_value')
    )
    op.add_column('orders', sa.Column('techSize', sa.String(), nullable=True))
    op.add_column('products', sa.Column('techSize', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'tokens', ['token_id'], ['id'])
    op.drop_column('users', 'wb_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wb_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'token_id')
    op.drop_column('products', 'techSize')
    op.drop_column('orders', 'techSize')
    op.drop_table('tokens')
    # ### end Alembic commands ###
