"""Add notify_cancel in users

Revision ID: 83d9a3b2c4a6
Revises: e01111499e9c
Create Date: 2025-04-25 16:38:52.144397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d9a3b2c4a6'
down_revision: Union[str, None] = 'e01111499e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notify_cancel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_cancel')
    # ### end Alembic commands ###
