"""Add token_id and techSize column to Sale

Revision ID: a5aecd6f24f9
Revises: 1b28355d5dea
Create Date: 2025-03-01 19:58:16.890840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5aecd6f24f9'
down_revision: Union[str, None] = '1b28355d5dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('token_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sales', 'tokens', ['token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'token_id')
    # ### end Alembic commands ###
