"""Add is_active in Token

Revision ID: d419a271eaa2
Revises: 83d9a3b2c4a6
Create Date: 2025-05-11 15:41:14.888881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd419a271eaa2'
down_revision: Union[str, None] = '83d9a3b2c4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tokens_is_active'), 'tokens', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_is_active'), table_name='tokens')
    op.drop_column('tokens', 'is_active')
    # ### end Alembic commands ###
