"""Add token_id column to orders

Revision ID: d548fff69967
Revises: 707f74e00c62
Create Date: 2025-03-01 15:28:54.210694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd548fff69967'
down_revision: Union[str, None] = '707f74e00c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('token_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'tokens', ['token_id'], ['id'])
    op.add_column('report_details', sa.Column('brand_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_details', 'brand_name')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'token_id')
    # ### end Alembic commands ###
