"""Add undefined  tables

Revision ID: e01111499e9c
Revises: 2774e1331510
Create Date: 2025-03-31 20:18:08.443179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e01111499e9c'
down_revision: Union[str, None] = '2774e1331510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('popular_request', 'vector')
    op.drop_constraint('uq_us er_warehouse', 'user_warehouses', type_='unique')
    op.create_unique_constraint('uq_user_warehouse', 'user_warehouses', ['user_id', 'warehouse_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_warehouse', 'user_warehouses', type_='unique')
    op.create_unique_constraint('uq_us er_warehouse', 'user_warehouses', ['user_id', 'warehouse_id'])
    op.add_column('popular_request', sa.Column('vector', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
